name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: dimerun-k4-ubuntu2204
    steps:
    - run: sudo loginctl enable-linger runner
    - uses: actions/checkout@v4
    - run: make
    - run: make -C podman_image build-en
